import Foundation

/// Built-in developer / product vocabulary: what the recognizer tends to hear → the correct spelling.
/// Applied before the user's dictionary (user entries win). Whole-word, case-insensitive.
public enum DevVocabulary {
    public struct Term: Sendable { public let word: String; public let heard: [String] }

    public static let terms: [Term] = [
        // AI tools
        Term(word: "Claude Code", heard: ["cloud code", "clod code", "claud code", "claude cod", "cloud coat"]),
        Term(word: "Claude", heard: ["claud", "clod ai", "cloud ai"]),
        Term(word: "Claude Desktop", heard: ["cloud desktop", "claude desktop"]),
        Term(word: "Anthropic", heard: ["and tropic", "anthropic", "an tropic", "anthropik"]),
        Term(word: "ChatGPT", heard: ["chat g p t", "chat gpt", "chat gbt", "chat jeep it"]),
        Term(word: "OpenAI", heard: ["open a i", "open ai", "open eye"]),
        Term(word: "Gemini", heard: ["gemini", "jem in i"]),
        Term(word: "Copilot", heard: ["co pilot", "copilot"]),
        Term(word: "Cursor", heard: ["cursor"]),
        Term(word: "Windsurf", heard: ["wind surf", "windsurf"]),
        Term(word: "Codex", heard: ["codex", "co decks"]),
        Term(word: "Ollama", heard: ["oh llama", "o llama", "ollama", "all llama"]),
        Term(word: "Hugging Face", heard: ["hugging face", "huggingface"]),
        Term(word: "LLM", heard: ["l l m", "llm"]),
        Term(word: "LLMs", heard: ["l l ms", "llms"]),
        Term(word: "MCP", heard: ["m c p", "mcp"]),
        Term(word: "Wispr Flow", heard: ["whisper flow", "wisper flow", "wispr flow"]),
        Term(word: "Whisper", heard: ["wisper"]),
        Term(word: "Parakeet", heard: ["para keet", "parakeet"]),
        Term(word: "CoreML", heard: ["core m l", "core ml", "coreml"]),
        Term(word: "MLX", heard: ["m l x", "mlx"]),
        Term(word: "PyTorch", heard: ["pie torch", "pi torch", "pytorch"]),
        Term(word: "TensorFlow", heard: ["tensor flow", "tensorflow"]),
        Term(word: "Vunu", heard: ["voo new", "vuno", "vunu", "vu new"]),
        Term(word: "Nunu", heard: ["new new", "nunu", "noo noo"]),
        // AI models & labs
        Term(word: "Fable", heard: ["fable model"]),
        Term(word: "Claude Fable", heard: ["claude fable", "cloud fable"]),
        Term(word: "Claude Mythos", heard: ["claude mythos", "cloud mythos", "claude mythose"]),
        Term(word: "Mythos", heard: ["mythos", "mythose"]),
        Term(word: "Claude Opus", heard: ["claude opus", "cloud opus"]),
        Term(word: "Claude Sonnet", heard: ["claude sonnet", "cloud sonnet", "claude sonet"]),
        Term(word: "Claude Haiku", heard: ["claude haiku", "cloud haiku", "claude hi coo"]),
        Term(word: "Opus", heard: ["opus model"]),
        Term(word: "Sonnet", heard: ["sonnet model", "sonet"]),
        Term(word: "Haiku", heard: ["haiku model", "hi coo"]),
        Term(word: "GPT-5", heard: ["g p t five", "gpt five", "gpt 5", "g p t 5", "chat g p t five"]),
        Term(word: "GPT-4o", heard: ["g p t four o", "gpt four o", "gpt 4 o", "gpt 4o"]),
        Term(word: "GPT-4", heard: ["g p t four", "gpt four", "gpt 4"]),
        Term(word: "o3", heard: ["o three model", "oh three model"]),
        Term(word: "o4-mini", heard: ["o four mini", "oh four mini"]),
        Term(word: "Gemini 2.5", heard: ["gemini two point five", "gemini 2.5"]),
        Term(word: "Gemini Flash", heard: ["gemini flash"]),
        Term(word: "Gemini Pro", heard: ["gemini pro"]),
        Term(word: "Gemma", heard: ["gemma"]),
        Term(word: "Llama", heard: ["llama model", "llama three", "llama 3", "llama four", "llama 4"]),
        Term(word: "Mistral", heard: ["mistral", "mistrel"]),
        Term(word: "Mixtral", heard: ["mixtral", "mix trell"]),
        Term(word: "DeepSeek", heard: ["deep seek", "deepseek"]),
        Term(word: "Qwen", heard: ["qwen", "quen", "kwen", "queen model"]),
        Term(word: "Grok", heard: ["grok", "grock"]),
        Term(word: "xAI", heard: ["x a i", "x ai"]),
        Term(word: "Phi", heard: ["phi model", "fi model"]),
        Term(word: "Kimi", heard: ["kimi", "kimmy k2", "kimi k2", "kimi k two"]),
        Term(word: "Perplexity", heard: ["perplexity"]),
        Term(word: "NotebookLM", heard: ["notebook l m", "notebook lm", "notebooklm"]),
        Term(word: "Midjourney", heard: ["mid journey", "midjourney"]),
        Term(word: "DALL·E", heard: ["dolly", "dall e", "dalle", "dali model"]),
        Term(word: "Stable Diffusion", heard: ["stable diffusion"]),
        Term(word: "Flux", heard: ["flux model", "flux dev", "flux pro"]),
        Term(word: "Sora", heard: ["sora", "sorah"]),
        Term(word: "Veo", heard: ["veo", "vayo", "vay oh"]),
        Term(word: "Runway", heard: ["runway ml", "runway gen"]),
        Term(word: "Higgsfield", heard: ["hexfields", "hex fields", "hexfield", "hex field", "higgs field", "higgsfield", "higsfield"]),
        Term(word: "Kling", heard: ["kling", "cling ai"]),
        Term(word: "Pika", heard: ["pika", "pika labs"]),
        Term(word: "Luma", heard: ["luma", "luma ai", "luma labs"]),
        Term(word: "Hailuo", heard: ["hailuo", "high low ai", "hi luo"]),
        Term(word: "Ideogram", heard: ["ideogram", "idea gram"]),
        Term(word: "Leonardo", heard: ["leonardo ai", "leonardo"]),
        Term(word: "Krea", heard: ["krea", "kre a", "crea"]),
        Term(word: "Recraft", heard: ["re craft", "recraft"]),
        Term(word: "Freepik", heard: ["free pick", "freepik", "free pik"]),
        Term(word: "ElevenLabs", heard: ["eleven labs", "elevenlabs", "11 labs"]),
        Term(word: "Suno", heard: ["suno", "sue no"]),
        Term(word: "Udio", heard: ["udio", "you dio"]),
        Term(word: "HeyGen", heard: ["hey gen", "heygen"]),
        Term(word: "Synthesia", heard: ["synthesia", "synthesia ai"]),
        Term(word: "Descript", heard: ["descript", "de script"]),
        Term(word: "ComfyUI", heard: ["comfy u i", "comfy ui", "comfyui"]),
        Term(word: "LoRA", heard: ["lora", "laura model", "low ra"]),
        Term(word: "ControlNet", heard: ["control net", "controlnet"]),
        Term(word: "Nano Banana", heard: ["nano banana"]),
        Term(word: "Imagen", heard: ["imagen", "image n"]),
        Term(word: "Whisper", heard: ["wisper"]),
        Term(word: "Character.AI", heard: ["character a i", "character ai"]),
        Term(word: "Manus", heard: ["manus", "man us ai"]),
        Term(word: "Genspark", heard: ["gen spark", "genspark"]),
        Term(word: "Devin", heard: ["devin ai"]),
        Term(word: "Jules", heard: ["jules agent"]),
        Term(word: "Codex CLI", heard: ["codex c l i", "codex cli"]),
        Term(word: "Gemini CLI", heard: ["gemini c l i", "gemini cli"]),
        Term(word: "Agent SDK", heard: ["agent s d k", "agent sdk"]),
        Term(word: "AGI", heard: ["a g i"]),
        Term(word: "RAG", heard: ["r a g", "rag pipeline"]),
        Term(word: "fine-tuning", heard: ["fine tuning", "finetuning"]),
        Term(word: "fine-tune", heard: ["fine tune", "finetune"]),
        Term(word: "embeddings", heard: ["embeddings", "in beddings"]),
        Term(word: "vector database", heard: ["vector database", "vector db"]),
        Term(word: "Pinecone", heard: ["pine cone db", "pinecone"]),
        Term(word: "Weaviate", heard: ["weaviate", "we v eight"]),
        Term(word: "LangChain", heard: ["lang chain", "langchain", "language chain"]),
        Term(word: "LangGraph", heard: ["lang graph", "langgraph"]),
        Term(word: "LlamaIndex", heard: ["llama index", "llamaindex"]),
        Term(word: "prompt engineering", heard: ["prompt engineering"]),
        Term(word: "system prompt", heard: ["system prompt"]),
        Term(word: "tokens", heard: ["tokens"]),
        Term(word: "context window", heard: ["context window"]),
        Term(word: "hallucination", heard: ["hallucination", "hallucinations"]),
        Term(word: "multimodal", heard: ["multi modal", "multimodal"]),
        Term(word: "text-to-image", heard: ["text to image"]),
        Term(word: "text-to-video", heard: ["text to video"]),
        Term(word: "image-to-video", heard: ["image to video"]),
        Term(word: "text-to-speech", heard: ["text to speech"]),
        Term(word: "speech-to-text", heard: ["speech to text"]),
        Term(word: "TTS", heard: ["t t s"]),
        Term(word: "STT", heard: ["s t t"]),
        Term(word: "ASR", heard: ["a s r"]),
        Term(word: "OCR", heard: ["o c r"]),
        Term(word: "GPU", heard: ["g p u"]),
        Term(word: "GPUs", heard: ["g p us", "g p u s"]),
        Term(word: "CUDA", heard: ["cuda", "kuda"]),
        Term(word: "inference", heard: ["inference"]),
        Term(word: "quantized", heard: ["quantized", "quantised"]),
        Term(word: "4-bit", heard: ["four bit", "4 bit"]),
        Term(word: "8-bit", heard: ["eight bit", "8 bit"]),
        // Design tools & UI vocabulary
        Term(word: "Dribbble", heard: ["dribble", "dribbble", "dribbel"]),
        Term(word: "Behance", heard: ["behance", "be hance", "bee hance"]),
        Term(word: "Mobbin", heard: ["morbin", "mobbin", "mobin", "mob in", "mor bin"]),
        Term(word: "Awwwards", heard: ["awwwards", "a wards site", "triple w awards"]),
        Term(word: "Pinterest", heard: ["pinterest", "pin interest"]),
        Term(word: "Unsplash", heard: ["un splash", "unsplash"]),
        Term(word: "Pexels", heard: ["pexels", "pixels stock"]),
        Term(word: "Canva", heard: ["canva", "can va"]),
        Term(word: "Sketch", heard: ["sketch app"]),
        Term(word: "Adobe XD", heard: ["adobe x d", "adobe xd"]),
        Term(word: "Photoshop", heard: ["photo shop", "photoshop"]),
        Term(word: "Illustrator", heard: ["illustrator"]),
        Term(word: "After Effects", heard: ["after effects", "aftereffects"]),
        Term(word: "Premiere Pro", heard: ["premiere pro", "premier pro"]),
        Term(word: "DaVinci Resolve", heard: ["davinci resolve", "da vinci resolve"]),
        Term(word: "Final Cut", heard: ["final cut"]),
        Term(word: "CapCut", heard: ["cap cut", "capcut"]),
        Term(word: "Lightroom", heard: ["light room", "lightroom"]),
        Term(word: "Blender", heard: ["blender"]),
        Term(word: "Cinema 4D", heard: ["cinema four d", "cinema 4 d", "cinema 4d"]),
        Term(word: "Spline", heard: ["spline", "spline 3d"]),
        Term(word: "Rive", heard: ["rive", "rive app", "ryve"]),
        Term(word: "Lottie", heard: ["lottie", "lotty", "lottie animation"]),
        Term(word: "Jitter", heard: ["jitter app"]),
        Term(word: "Protopie", heard: ["proto pie", "protopie"]),
        Term(word: "Zeplin", heard: ["zeplin", "zeppelin design"]),
        Term(word: "Storyset", heard: ["story set", "storyset"]),
        Term(word: "Iconify", heard: ["iconify"]),
        Term(word: "Lucide", heard: ["lucide", "lucid icons", "lucide icons"]),
        Term(word: "Heroicons", heard: ["hero icons", "heroicons"]),
        Term(word: "Font Awesome", heard: ["font awesome"]),
        Term(word: "Google Fonts", heard: ["google fonts"]),
        Term(word: "Inter", heard: ["inter font"]),
        Term(word: "Figtree", heard: ["fig tree", "figtree"]),
        Term(word: "Material Design", heard: ["material design"]),
        Term(word: "Material UI", heard: ["material u i", "material ui"]),
        Term(word: "Ant Design", heard: ["ant design"]),
        Term(word: "Chakra UI", heard: ["chakra u i", "chakra ui"]),
        Term(word: "Radix", heard: ["radix", "radix ui", "radix u i"]),
        Term(word: "Aceternity", heard: ["aceternity", "a ceternity", "eternity ui"]),
        Term(word: "Magic UI", heard: ["magic u i", "magic ui"]),
        Term(word: "Framer Motion", heard: ["framer motion"]),
        Term(word: "GSAP", heard: ["g sap", "gsap", "g s a p"]),
        Term(word: "Three.js", heard: ["three js", "three j s", "threejs"]),
        Term(word: "WebGL", heard: ["web g l", "webgl", "web gl"]),
        Term(word: "Bento grid", heard: ["bento grid"]),
        Term(word: "glassmorphism", heard: ["glass morphism", "glassmorphism"]),
        Term(word: "neumorphism", heard: ["new morphism", "neumorphism", "neo morphism"]),
        Term(word: "skeuomorphic", heard: ["skeuomorphic", "skew morphic"]),
        Term(word: "hero section", heard: ["hero section"]),
        Term(word: "navbar", heard: ["nav bar", "navbar"]),
        Term(word: "sidebar", heard: ["side bar", "sidebar"]),
        Term(word: "footer", heard: ["footer"]),
        Term(word: "CTA", heard: ["c t a"]),
        Term(word: "CTAs", heard: ["c t as", "c t a s"]),
        Term(word: "dropdown", heard: ["drop down", "dropdown"]),
        Term(word: "modal", heard: ["modal"]),
        Term(word: "tooltip", heard: ["tool tip", "tooltip"]),
        Term(word: "toast", heard: ["toast notification"]),
        Term(word: "onboarding", heard: ["on boarding", "onboarding"]),
        Term(word: "wireframe", heard: ["wire frame", "wireframe"]),
        Term(word: "wireframes", heard: ["wire frames", "wireframes"]),
        Term(word: "mockup", heard: ["mock up", "mockup"]),
        Term(word: "mockups", heard: ["mock ups", "mockups"]),
        Term(word: "prototype", heard: ["prototype", "proto type"]),
        Term(word: "design system", heard: ["design system"]),
        Term(word: "design tokens", heard: ["design tokens"]),
        Term(word: "dark mode", heard: ["dark mode"]),
        Term(word: "light mode", heard: ["light mode"]),
        Term(word: "responsive", heard: ["responsive"]),
        Term(word: "breakpoint", heard: ["break point", "breakpoint"]),
        Term(word: "breakpoints", heard: ["break points", "breakpoints"]),
        Term(word: "padding", heard: ["padding"]),
        Term(word: "margin", heard: ["margin"]),
        Term(word: "border radius", heard: ["border radius"]),
        Term(word: "drop shadow", heard: ["drop shadow"]),
        Term(word: "gradient", heard: ["gradient"]),
        Term(word: "kerning", heard: ["kerning", "curning"]),
        Term(word: "line height", heard: ["line height"]),
        Term(word: "letter spacing", heard: ["letter spacing"]),
        Term(word: "auto layout", heard: ["auto layout", "autolayout"]),
        Term(word: "flexbox", heard: ["flex box", "flexbox"]),
        Term(word: "CSS Grid", heard: ["c s s grid", "css grid"]),
        Term(word: "z-index", heard: ["z index", "zed index"]),
        Term(word: "viewport", heard: ["view port", "viewport"]),
        Term(word: "favicon", heard: ["fav icon", "favicon"]),
        Term(word: "SVG", heard: ["s v g"]),
        Term(word: "PNG", heard: ["p n g"]),
        Term(word: "JPEG", heard: ["j peg", "jpeg"]),
        Term(word: "WebP", heard: ["web p", "webp"]),
        Term(word: "hex code", heard: ["hex code"]),
        Term(word: "RGB", heard: ["r g b"]),
        Term(word: "HSL", heard: ["h s l"]),
        Term(word: "UI kit", heard: ["u i kit"]),
        Term(word: "landing page", heard: ["landing page"]),
        Term(word: "SaaS landing page", heard: ["sass landing page", "saas landing page"]),
        Term(word: "A/B test", heard: ["a b test", "a slash b test"]),
        Term(word: "user flow", heard: ["user flow"]),
        Term(word: "user journey", heard: ["user journey"]),
        Term(word: "persona", heard: ["persona"]),
        Term(word: "usability", heard: ["usability"]),
        Term(word: "accessibility", heard: ["accessibility"]),
        Term(word: "a11y", heard: ["a eleven y", "a 11 y", "ally spec"]),
        Term(word: "i18n", heard: ["i eighteen n", "i 18 n"]),
        Term(word: "WCAG", heard: ["w c a g", "wcag", "wuh cag"]),
        // Backends, databases, auth
        Term(word: "Supabase", heard: ["super base", "superbase", "super pace", "supa base", "soup a base", "suppa base", "supabase", "super bass", "super pays"]),
        Term(word: "Postgres", heard: ["postgress", "post gres", "post grass", "post gress", "postgre", "postgres", "post grease"]),
        Term(word: "PostgreSQL", heard: ["postgre s q l", "postgres q l", "postgresql", "postgre sequel"]),
        Term(word: "Keycloak", heard: ["key clock", "key cloak", "keycloak", "key cloke"]),
        Term(word: "Directus", heard: ["direct us", "directus", "direct is"]),
        Term(word: "Firebase", heard: ["fire base", "firebase"]),
        Term(word: "Firestore", heard: ["fire store", "firestore"]),
        Term(word: "MongoDB", heard: ["mongo d b", "mongo db", "mongodb", "mongo database"]),
        Term(word: "Redis", heard: ["reddis", "redis", "red iss"]),
        Term(word: "MySQL", heard: ["my s q l", "my sequel", "mysql"]),
        Term(word: "SQLite", heard: ["s q lite", "sequel light", "sqlite", "sequel lite"]),
        Term(word: "SQL", heard: ["s q l"]),
        Term(word: "Prisma", heard: ["prizma", "prisma"]),
        Term(word: "GraphQL", heard: ["graph q l", "graph ql", "graphql", "graph cue el"]),
        Term(word: "tRPC", heard: ["t r p c", "trpc", "tea r p c"]),
        Term(word: "gRPC", heard: ["g r p c", "grpc"]),
        Term(word: "REST API", heard: ["rest a p i", "rest api"]),
        Term(word: "OAuth", heard: ["o auth", "oh auth", "oauth", "oh off"]),
        Term(word: "Auth0", heard: ["auth zero", "auth 0", "off zero"]),
        Term(word: "JWT", heard: ["j w t", "jwt"]),
        Term(word: "Twilio", heard: ["twill io", "twilio", "twill e o"]),
        Term(word: "SendGrid", heard: ["send grid", "sendgrid"]),
        Term(word: "Convex", heard: ["convex"]),
        Term(word: "PlanetScale", heard: ["planet scale", "planetscale"]),
        Term(word: "Neon", heard: ["neon db"]),
        Term(word: "Upstash", heard: ["up stash", "upstash"]),
        Term(word: "Elasticsearch", heard: ["elastic search", "elasticsearch"]),
        Term(word: "Kafka", heard: ["kafka"]),
        Term(word: "RabbitMQ", heard: ["rabbit m q", "rabbitmq", "rabbit em queue"]),
        Term(word: "Hasura", heard: ["hasura", "ha sura"]),
        Term(word: "PocketBase", heard: ["pocket base", "pocketbase"]),
        Term(word: "Appwrite", heard: ["app write", "appwrite"]),
        Term(word: "Payload CMS", heard: ["payload c m s", "payload cms"]),
        Term(word: "Strapi", heard: ["strappy", "strapi", "strap e"]),
        Term(word: "Contentful", heard: ["contentful"]),
        // Frontend & frameworks
        Term(word: "Next.js", heard: ["next js", "next j s", "nextjs", "next dot js", "next jay s"]),
        Term(word: "Node.js", heard: ["node js", "node j s", "nodejs", "node dot js"]),
        Term(word: "Vue.js", heard: ["vue js", "view js", "vuejs", "view j s"]),
        Term(word: "Nuxt", heard: ["nuxt", "nucst", "nux t"]),
        Term(word: "React", heard: ["react js", "react j s", "reactjs"]),
        Term(word: "React Native", heard: ["react native"]),
        Term(word: "Svelte", heard: ["svelte", "swelt"]),
        Term(word: "SvelteKit", heard: ["svelte kit", "sveltekit"]),
        Term(word: "Angular", heard: ["angular"]),
        Term(word: "Vite", heard: ["veet", "vight", "vite", "v e t"]),
        Term(word: "Vitest", heard: ["vi test", "vee test", "vitest"]),
        Term(word: "Tailwind", heard: ["tail wind", "tailwind"]),
        Term(word: "shadcn", heard: ["shad c n", "shad cn", "shadcn", "shad see en", "chad cn"]),
        Term(word: "TypeScript", heard: ["type script", "typescript"]),
        Term(word: "JavaScript", heard: ["java script", "javascript"]),
        Term(word: "HTML", heard: ["h t m l"]),
        Term(word: "CSS", heard: ["c s s"]),
        Term(word: "ESLint", heard: ["e s lint", "es lint", "eslint"]),
        Term(word: "Prettier", heard: ["prettier"]),
        Term(word: "Playwright", heard: ["play write", "play right", "playwright"]),
        Term(word: "Puppeteer", heard: ["puppeteer"]),
        Term(word: "Storybook", heard: ["story book", "storybook"]),
        Term(word: "Webpack", heard: ["web pack", "webpack"]),
        Term(word: "Turbopack", heard: ["turbo pack", "turbopack"]),
        Term(word: "Turborepo", heard: ["turbo repo", "turborepo"]),
        Term(word: "monorepo", heard: ["mono repo", "monorepo"]),
        Term(word: "npm", heard: ["n p m"]),
        Term(word: "pnpm", heard: ["p n p m", "pnpm"]),
        Term(word: "Yarn", heard: ["yarn"]),
        Term(word: "Bun", heard: ["bun js"]),
        Term(word: "Deno", heard: ["deno", "dee no"]),
        Term(word: "Electron", heard: ["electron"]),
        Term(word: "Tauri", heard: ["tao ree", "tauri", "tory app"]),
        Term(word: "Expo", heard: ["expo"]),
        Term(word: "Flutter", heard: ["flutter"]),
        Term(word: "SwiftUI", heard: ["swift u i", "swift ui", "swiftui"]),
        Term(word: "Xcode", heard: ["x code", "ex code", "xcode"]),
        Term(word: "XcodeGen", heard: ["x code gen", "xcodegen", "xcode gen"]),
        Term(word: "iOS", heard: ["i o s", "ios"]),
        Term(word: "macOS", heard: ["mac o s", "mac os", "macos"]),
        Term(word: "iPadOS", heard: ["ipad o s", "ipad os"]),
        Term(word: "watchOS", heard: ["watch o s", "watch os"]),
        Term(word: "UIKit", heard: ["u i kit", "ui kit", "uikit"]),
        Term(word: "AppKit", heard: ["app kit", "appkit"]),
        // Languages & backends
        Term(word: "Python", heard: ["python"]),
        Term(word: "FastAPI", heard: ["fast a p i", "fast api", "fastapi"]),
        Term(word: "Django", heard: ["jango", "django"]),
        Term(word: "Flask", heard: ["flask"]),
        Term(word: "Laravel", heard: ["lara vel", "laravel", "lara vell"]),
        Term(word: "PHP", heard: ["p h p"]),
        Term(word: "Golang", heard: ["go lang", "golang"]),
        Term(word: "Rust", heard: ["rust lang"]),
        Term(word: "Kotlin", heard: ["kotlin", "cot lin"]),
        Term(word: "C#", heard: ["c sharp"]),
        Term(word: "C++", heard: ["c plus plus"]),
        Term(word: ".NET", heard: ["dot net"]),
        Term(word: "Spring Boot", heard: ["spring boot"]),
        Term(word: "Elixir", heard: ["elixir"]),
        Term(word: "Zig", heard: ["zig lang"]),
        // Infra, DevOps, cloud
        Term(word: "Docker", heard: ["docker"]),
        Term(word: "Docker Compose", heard: ["docker compose"]),
        Term(word: "Kubernetes", heard: ["kubernetes", "cooper netties", "cooper nettis", "k8s", "k 8 s"]),
        Term(word: "Nginx", heard: ["engine x", "engine ex", "nginx", "n ginx"]),
        Term(word: "Traefik", heard: ["traefik"]),
        Term(word: "Terraform", heard: ["terra form", "terraform"]),
        Term(word: "Ansible", heard: ["ansible"]),
        Term(word: "Jenkins", heard: ["jenkins"]),
        Term(word: "CI/CD", heard: ["c i c d", "ci cd", "c i slash c d", "ci slash cd"]),
        Term(word: "GitHub", heard: ["get hub", "git hub", "github"]),
        Term(word: "GitHub Actions", heard: ["github actions", "get hub actions"]),
        Term(word: "GitLab", heard: ["get lab", "git lab", "gitlab"]),
        Term(word: "Bitbucket", heard: ["bit bucket", "bitbucket"]),
        Term(word: "Vercel", heard: ["versal", "ver cell", "vercell", "verso", "vercel", "versel"]),
        Term(word: "Netlify", heard: ["net lify", "netlify", "netla fie"]),
        Term(word: "Cloudflare", heard: ["cloud flare", "cloudflare", "cloud flair"]),
        Term(word: "Cloudflare Workers", heard: ["cloudflare workers", "cloud flare workers"]),
        Term(word: "AWS", heard: ["a w s", "aws"]),
        Term(word: "S3", heard: ["s three"]),
        Term(word: "EC2", heard: ["e c two", "e c 2"]),
        Term(word: "DynamoDB", heard: ["dynamo d b", "dynamo db", "dynamodb"]),
        Term(word: "Azure", heard: ["azure"]),
        Term(word: "GCP", heard: ["g c p"]),
        Term(word: "Google Cloud", heard: ["google cloud"]),
        Term(word: "DigitalOcean", heard: ["digital ocean", "digitalocean"]),
        Term(word: "Hetzner", heard: ["hetzner", "het snur"]),
        Term(word: "Railway", heard: ["railway app"]),
        Term(word: "Render", heard: ["render dot com"]),
        Term(word: "Fly.io", heard: ["fly i o", "fly io", "fly dot io"]),
        Term(word: "Coolify", heard: ["cool ify", "coolify"]),
        Term(word: "Namecheap", heard: ["name cheap", "name chip", "neme name chip", "namecheap", "name sheep"]),
        Term(word: "GoDaddy", heard: ["go daddy", "godaddy"]),
        Term(word: "Porkbun", heard: ["pork bun", "porkbun"]),
        Term(word: "Squarespace", heard: ["square space", "squarespace"]),
        Term(word: "Wix", heard: ["wix", "wicks site"]),
        Term(word: "Hostinger", heard: ["hostinger", "host inger"]),
        Term(word: "Bluehost", heard: ["blue host", "bluehost"]),
        Term(word: "Cloudflare Pages", heard: ["cloudflare pages", "cloud flare pages"]),
        Term(word: "Cloudflare R2", heard: ["cloudflare r two", "cloudflare r2", "cloud flare r two"]),
        Term(word: "Vercel AI SDK", heard: ["vercel a i s d k", "vercel ai sdk", "versal ai sdk"]),
        Term(word: "Lovable", heard: ["loveable", "lovable", "lovable dev"]),
        Term(word: "Replit Agent", heard: ["replit agent", "repl it agent"]),
        Term(word: "Base44", heard: ["base forty four", "base 44"]),
        Term(word: "Emergent", heard: ["emergent ai"]),
        Term(word: "Softr", heard: ["softer app", "softr"]),
        Term(word: "Glide", heard: ["glide apps"]),
        Term(word: "FlutterFlow", heard: ["flutter flow", "flutterflow"]),
        Term(word: "Xano", heard: ["xano", "zano backend"]),
        Term(word: "Backendless", heard: ["backend less", "backendless"]),
        Term(word: "Nhost", heard: ["n host", "nhost"]),
        Term(word: "Better Auth", heard: ["better auth", "better off library"]),
        Term(word: "NextAuth", heard: ["next auth", "nextauth"]),
        Term(word: "Lemon Squeezy", heard: ["lemon squeezy", "lemonsqueezy"]),
        Term(word: "Paddle", heard: ["paddle billing"]),
        Term(word: "Polar", heard: ["polar sh", "polar dot sh"]),
        Term(word: "Loops", heard: ["loops email"]),
        Term(word: "Mailchimp", heard: ["mail chimp", "mailchimp"]),
        Term(word: "Brevo", heard: ["brevo"]),
        Term(word: "Intercom", heard: ["intercom"]),
        Term(word: "Crisp", heard: ["crisp chat"]),
        Term(word: "Typeform", heard: ["type form", "typeform"]),
        Term(word: "Tally", heard: ["tally forms"]),
        Term(word: "Calendly", heard: ["calendly", "calendar ly"]),
        Term(word: "Cal.com", heard: ["cal dot com"]),
        Term(word: "Umami", heard: ["umami analytics"]),
        Term(word: "Plausible", heard: ["plausible analytics"]),
        Term(word: "Dokploy", heard: ["dock ploy", "dokploy"]),
        Term(word: "Portainer", heard: ["portainer", "port tainer"]),
        Term(word: "Proxmox", heard: ["prox mox", "proxmox"]),
        Term(word: "Tailscale", heard: ["tail scale", "tailscale"]),
        Term(word: "WireGuard", heard: ["wire guard", "wireguard"]),
        Term(word: "SSH", heard: ["s s h"]),
        Term(word: "SSL", heard: ["s s l"]),
        Term(word: "TLS", heard: ["t l s"]),
        Term(word: "HTTPS", heard: ["h t t p s"]),
        Term(word: "HTTP", heard: ["h t t p"]),
        Term(word: "DNS", heard: ["d n s"]),
        Term(word: "CDN", heard: ["c d n"]),
        Term(word: "VPN", heard: ["v p n"]),
        Term(word: "VPS", heard: ["v p s"]),
        Term(word: "IP address", heard: ["i p address"]),
        Term(word: "localhost", heard: ["local host", "localhost"]),
        Term(word: "webhook", heard: ["web hook", "webhook"]),
        Term(word: "webhooks", heard: ["web hooks", "webhooks"]),
        Term(word: "WebSocket", heard: ["web socket", "websocket"]),
        Term(word: "WebSockets", heard: ["web sockets", "websockets"]),
        Term(word: "cron job", heard: ["chron job", "cron job", "crown job"]),
        Term(word: "Grafana", heard: ["grafana", "gra fauna"]),
        Term(word: "Prometheus", heard: ["prometheus"]),
        Term(word: "Datadog", heard: ["data dog", "datadog"]),
        Term(word: "Sentry", heard: ["sentry"]),
        Term(word: "PostHog", heard: ["post hog", "posthog"]),
        Term(word: "Mixpanel", heard: ["mix panel", "mixpanel"]),
        // APIs, formats, general
        Term(word: "API", heard: ["a p i"]),
        Term(word: "APIs", heard: ["a p i s", "a p is"]),
        Term(word: "OpenAPI", heard: ["open a p i", "open api", "openapi"]),
        Term(word: "Swagger", heard: ["swagger"]),
        Term(word: "Postman", heard: ["post man", "postman"]),
        Term(word: "JSON", heard: ["j son", "jay son", "json"]),
        Term(word: "YAML", heard: ["yaml", "yam el", "yammel"]),
        Term(word: "TOML", heard: ["toml", "tom el"]),
        Term(word: "CSV", heard: ["c s v"]),
        Term(word: "XML", heard: ["x m l"]),
        Term(word: "PDF", heard: ["p d f"]),
        Term(word: "URL", heard: ["u r l"]),
        Term(word: "URLs", heard: ["u r ls", "u r l s"]),
        Term(word: "UUID", heard: ["u u i d", "uuid"]),
        Term(word: "CLI", heard: ["c l i"]),
        Term(word: "SDK", heard: ["s d k"]),
        Term(word: "SDKs", heard: ["s d ks", "s d k s"]),
        Term(word: "UI", heard: ["u i"]),
        Term(word: "UX", heard: ["u x"]),
        Term(word: "UI/UX", heard: ["u i u x", "ui ux", "u i slash u x"]),
        Term(word: "SaaS", heard: ["s a a s", "saas"]),
        Term(word: "MVP", heard: ["m v p"]),
        Term(word: "CRUD", heard: ["crud"]),
        Term(word: "ORM", heard: ["o r m"]),
        Term(word: "regex", heard: ["reg ex", "regex", "reg x"]),
        Term(word: "backend", heard: ["back end", "backend"]),
        Term(word: "frontend", heard: ["front end", "frontend"]),
        Term(word: "full-stack", heard: ["full stack", "fullstack"]),
        Term(word: "microservices", heard: ["micro services", "microservices"]),
        Term(word: "serverless", heard: ["server less", "serverless"]),
        Term(word: "middleware", heard: ["middle ware", "middleware"]),
        Term(word: "README", heard: ["read me file", "readme"]),
        Term(word: ".env", heard: ["dot env", "dot e n v"]),
        Term(word: "env var", heard: ["env var", "e n v var"]),
        Term(word: "env vars", heard: ["env vars", "e n v vars"]),
        Term(word: "PR", heard: ["p r"]),
        Term(word: "PRs", heard: ["p rs", "p r s"]),
        Term(word: "repo", heard: ["repo"]),
        Term(word: "MCP server", heard: ["m c p server", "mcp server"]),
        // Tools & products
        Term(word: "Figma", heard: ["fig ma", "figma", "fig mah"]),
        Term(word: "FigJam", heard: ["fig jam", "figjam"]),
        Term(word: "Framer", heard: ["framer"]),
        Term(word: "Webflow", heard: ["web flow", "webflow"]),
        Term(word: "WordPress", heard: ["word press", "wordpress"]),
        Term(word: "Shopify", heard: ["shopify", "shop ify"]),
        Term(word: "Notion", heard: ["notion"]),
        Term(word: "Slack", heard: ["slack"]),
        Term(word: "Jira", heard: ["jeera", "jira", "gira"]),
        Term(word: "Trello", heard: ["trello"]),
        Term(word: "Asana", heard: ["asana"]),
        Term(word: "ClickUp", heard: ["click up", "clickup"]),
        Term(word: "Airtable", heard: ["air table", "airtable"]),
        Term(word: "Zapier", heard: ["zap ier", "zapier", "zappier"]),
        Term(word: "n8n", heard: ["n eight n", "n 8 n", "n8n", "n a 10"]),
        Term(word: "Make.com", heard: ["make dot com"]),
        Term(word: "Retool", heard: ["re tool", "retool"]),
        Term(word: "Bolt", heard: ["bolt new", "bolt dot new"]),
        Term(word: "v0", heard: ["v zero", "vee zero"]),
        Term(word: "Replit", heard: ["repl it", "replit", "rep lit"]),
        Term(word: "VS Code", heard: ["v s code", "vs code", "vscode", "visual studio code"]),
        Term(word: "Neovim", heard: ["neo vim", "neovim"]),
        Term(word: "Ghostty", heard: ["ghosty", "ghost tea", "ghostty", "ghost e"]),
        Term(word: "iTerm", heard: ["i term", "iterm", "eye term"]),
        Term(word: "iTerm2", heard: ["i term two", "iterm2", "i term 2"]),
        Term(word: "tmux", heard: ["t mux", "tmux", "tea mux"]),
        Term(word: "zsh", heard: ["z s h", "zish", "zsh", "z shell"]),
        Term(word: "Homebrew", heard: ["home brew", "homebrew"]),
        Term(word: "brew install", heard: ["brew install"]),
        Term(word: "Raycast", heard: ["ray cast", "raycast"]),
        Term(word: "1Password", heard: ["one password", "1 password", "1password"]),
        Term(word: "Obsidian", heard: ["obsidian"]),
        Term(word: "Arc browser", heard: ["arc browser"]),
        Term(word: "Zen Browser", heard: ["zen browser"]),
        Term(word: "Chrome DevTools", heard: ["chrome dev tools", "chrome devtools"]),
        Term(word: "DevTools", heard: ["dev tools", "devtools"]),
        Term(word: "Xcode Cloud", heard: ["xcode cloud", "x code cloud"]),
        Term(word: "TestFlight", heard: ["test flight", "testflight"]),
        Term(word: "App Store Connect", heard: ["app store connect"]),
        Term(word: "Google Analytics", heard: ["google analytics"]),
        Term(word: "Google Sheets", heard: ["google sheets"]),
        Term(word: "Google Drive", heard: ["google drive"]),
        Term(word: "Gmail", heard: ["g mail", "gmail"]),
        Term(word: "Outlook", heard: ["outlook"]),
        Term(word: "Microsoft Teams", heard: ["microsoft teams"]),
        Term(word: "WhatsApp", heard: ["whats app", "whatsapp", "what's app"]),
        Term(word: "Telegram", heard: ["telegram"]),
        Term(word: "LinkedIn", heard: ["linked in", "linkedin"]),
        Term(word: "YouTube", heard: ["you tube", "youtube"]),
        Term(word: "TikTok", heard: ["tik tok", "tiktok"]),
        Term(word: "Instagram", heard: ["instagram", "insta gram"]),
        Term(word: "Spotify", heard: ["spotify"]),
        Term(word: "Apple Music", heard: ["apple music"]),
        Term(word: "iPhone", heard: ["i phone", "iphone"]),
        Term(word: "iPad", heard: ["i pad", "ipad"]),
        Term(word: "MacBook", heard: ["mac book", "macbook"]),
        Term(word: "MacBook Air", heard: ["mac book air", "macbook air"]),
        Term(word: "MacBook Pro", heard: ["mac book pro", "macbook pro"]),
        Term(word: "Apple Silicon", heard: ["apple silicon"]),
        Term(word: "Apple Intelligence", heard: ["apple intelligence"]),
        Term(word: "Neural Engine", heard: ["neural engine"]),
        Term(word: "Wi-Fi", heard: ["wifi", "wi fi", "why fi"]),
        Term(word: "Bluetooth", heard: ["blue tooth", "bluetooth"]),
        Term(word: "AirPods", heard: ["air pods", "airpods"]),
        Term(word: "USB-C", heard: ["u s b c", "usb c", "usb see"]),
    ]

    /// Sorted longest-phrase-first so "claude code" wins over "claude".
    static let compiled: [(re: NSRegularExpression, word: String, probe: String)] = {
        var list: [(String, String)] = []
        for t in terms { for h in t.heard { list.append((h, t.word)) } }
        list.sort { $0.0.count > $1.0.count }
        return list.map { (TextUtil.regex("(?<![\\w.@/-])" + NSRegularExpression.escapedPattern(for: $0.0) + "(?![\\w.@/-])"), $0.1, String($0.0.split(separator: " ")[0])) }
    }()

    static func wordSet(_ s: String) -> Set<String> {
        Set(s.lowercased().split { !($0.isLetter || $0.isNumber) }.map(String.init))
    }

    public static func apply(_ text: String) -> String {
        var out = text
        var words = wordSet(text)
        for (re, word, probe) in compiled where words.contains(probe) {   // O(1) first-word probe before the regex
            let replaced = re.stringByReplacingMatches(in: out, range: NSRange(out.startIndex..., in: out), withTemplate: NSRegularExpression.escapedTemplate(for: word))
            if replaced != out { out = replaced; words = wordSet(out) }
        }
        return out
    }

    /// Terms present in `text` (to tell the LLM to preserve them).
    public static func termsPresent(in text: String) -> [String] {
        let lower = text.lowercased()
        return terms.map(\.word).filter { lower.contains($0.lowercased()) }
    }
}
