import Foundation

/// Built-in developer / product vocabulary: what the recognizer tends to hear → the correct spelling.
/// Applied before the user's dictionary (user entries win). Whole-word, case-insensitive.
public enum DevVocabulary {
    public struct Term: Sendable { public let word: String; public let heard: [String] }

    public static let terms: [Term] = [
        // AI tools
        Term(word: "Claude Code", heard: ["cloud code", "clod code", "claud code", "claude cod", "cloud coat"]),
        Term(word: "Claude", heard: ["claud", "clod ai", "cloud ai"]),
        Term(word: "Claude Desktop", heard: ["cloud desktop", "claude desktop"]),
        Term(word: "Anthropic", heard: ["and tropic", "anthropic", "an tropic", "anthropik"]),
        Term(word: "ChatGPT", heard: ["chat g p t", "chat gpt", "chat gbt", "chat jeep it"]),
        Term(word: "OpenAI", heard: ["open a i", "open ai", "open eye"]),
        Term(word: "Gemini", heard: ["gemini", "jem in i"]),
        Term(word: "Copilot", heard: ["co pilot", "copilot"]),
        Term(word: "Cursor", heard: ["cursor"]),
        Term(word: "Windsurf", heard: ["wind surf", "windsurf"]),
        Term(word: "Codex", heard: ["codex", "co decks"]),
        Term(word: "Ollama", heard: ["oh llama", "o llama", "ollama", "all llama"]),
        Term(word: "Hugging Face", heard: ["hugging face", "huggingface"]),
        Term(word: "LLM", heard: ["l l m", "llm"]),
        Term(word: "LLMs", heard: ["l l ms", "llms"]),
        Term(word: "MCP", heard: ["m c p", "mcp"]),
        Term(word: "Wispr Flow", heard: ["whisper flow", "wisper flow", "wispr flow"]),
        Term(word: "Whisper", heard: ["wisper"]),
        Term(word: "Parakeet", heard: ["para keet", "parakeet"]),
        Term(word: "CoreML", heard: ["core m l", "core ml", "coreml"]),
        Term(word: "MLX", heard: ["m l x", "mlx"]),
        Term(word: "PyTorch", heard: ["pie torch", "pi torch", "pytorch"]),
        Term(word: "TensorFlow", heard: ["tensor flow", "tensorflow"]),
        Term(word: "Vunu", heard: ["voo new", "vuno", "vunu", "vu new"]),
        Term(word: "Nunu", heard: ["new new", "nunu", "noo noo"]),
        // Backends, databases, auth
        Term(word: "Supabase", heard: ["super base", "superbase", "super pace", "supa base", "soup a base", "suppa base", "supabase", "super bass", "super pays"]),
        Term(word: "Postgres", heard: ["postgress", "post gres", "post grass", "post gress", "postgre", "postgres", "post grease"]),
        Term(word: "PostgreSQL", heard: ["postgre s q l", "postgres q l", "postgresql", "postgre sequel"]),
        Term(word: "Keycloak", heard: ["key clock", "key cloak", "keycloak", "key cloke"]),
        Term(word: "Directus", heard: ["direct us", "directus", "direct is"]),
        Term(word: "Firebase", heard: ["fire base", "firebase"]),
        Term(word: "Firestore", heard: ["fire store", "firestore"]),
        Term(word: "MongoDB", heard: ["mongo d b", "mongo db", "mongodb", "mongo database"]),
        Term(word: "Redis", heard: ["reddis", "redis", "red iss"]),
        Term(word: "MySQL", heard: ["my s q l", "my sequel", "mysql"]),
        Term(word: "SQLite", heard: ["s q lite", "sequel light", "sqlite", "sequel lite"]),
        Term(word: "SQL", heard: ["s q l"]),
        Term(word: "Prisma", heard: ["prizma", "prisma"]),
        Term(word: "GraphQL", heard: ["graph q l", "graph ql", "graphql", "graph cue el"]),
        Term(word: "tRPC", heard: ["t r p c", "trpc", "tea r p c"]),
        Term(word: "gRPC", heard: ["g r p c", "grpc"]),
        Term(word: "REST API", heard: ["rest a p i", "rest api"]),
        Term(word: "OAuth", heard: ["o auth", "oh auth", "oauth", "oh off"]),
        Term(word: "Auth0", heard: ["auth zero", "auth 0", "off zero"]),
        Term(word: "JWT", heard: ["j w t", "jwt"]),
        Term(word: "Twilio", heard: ["twill io", "twilio", "twill e o"]),
        Term(word: "SendGrid", heard: ["send grid", "sendgrid"]),
        Term(word: "Convex", heard: ["convex"]),
        Term(word: "PlanetScale", heard: ["planet scale", "planetscale"]),
        Term(word: "Neon", heard: ["neon db"]),
        Term(word: "Upstash", heard: ["up stash", "upstash"]),
        Term(word: "Elasticsearch", heard: ["elastic search", "elasticsearch"]),
        Term(word: "Kafka", heard: ["kafka"]),
        Term(word: "RabbitMQ", heard: ["rabbit m q", "rabbitmq", "rabbit em queue"]),
        Term(word: "Hasura", heard: ["hasura", "ha sura"]),
        Term(word: "PocketBase", heard: ["pocket base", "pocketbase"]),
        Term(word: "Appwrite", heard: ["app write", "appwrite"]),
        Term(word: "Payload CMS", heard: ["payload c m s", "payload cms"]),
        Term(word: "Strapi", heard: ["strappy", "strapi", "strap e"]),
        Term(word: "Contentful", heard: ["contentful"]),
        // Frontend & frameworks
        Term(word: "Next.js", heard: ["next js", "next j s", "nextjs", "next dot js", "next jay s"]),
        Term(word: "Node.js", heard: ["node js", "node j s", "nodejs", "node dot js"]),
        Term(word: "Vue.js", heard: ["vue js", "view js", "vuejs", "view j s"]),
        Term(word: "Nuxt", heard: ["nuxt", "nucst", "nux t"]),
        Term(word: "React", heard: ["react js", "react j s", "reactjs"]),
        Term(word: "React Native", heard: ["react native"]),
        Term(word: "Svelte", heard: ["svelte", "swelt"]),
        Term(word: "SvelteKit", heard: ["svelte kit", "sveltekit"]),
        Term(word: "Angular", heard: ["angular"]),
        Term(word: "Vite", heard: ["veet", "vight", "vite", "v e t"]),
        Term(word: "Vitest", heard: ["vi test", "vee test", "vitest"]),
        Term(word: "Tailwind", heard: ["tail wind", "tailwind"]),
        Term(word: "shadcn", heard: ["shad c n", "shad cn", "shadcn", "shad see en", "chad cn"]),
        Term(word: "TypeScript", heard: ["type script", "typescript"]),
        Term(word: "JavaScript", heard: ["java script", "javascript"]),
        Term(word: "HTML", heard: ["h t m l"]),
        Term(word: "CSS", heard: ["c s s"]),
        Term(word: "ESLint", heard: ["e s lint", "es lint", "eslint"]),
        Term(word: "Prettier", heard: ["prettier"]),
        Term(word: "Playwright", heard: ["play write", "play right", "playwright"]),
        Term(word: "Puppeteer", heard: ["puppeteer"]),
        Term(word: "Storybook", heard: ["story book", "storybook"]),
        Term(word: "Webpack", heard: ["web pack", "webpack"]),
        Term(word: "Turbopack", heard: ["turbo pack", "turbopack"]),
        Term(word: "Turborepo", heard: ["turbo repo", "turborepo"]),
        Term(word: "monorepo", heard: ["mono repo", "monorepo"]),
        Term(word: "npm", heard: ["n p m"]),
        Term(word: "pnpm", heard: ["p n p m", "pnpm"]),
        Term(word: "Yarn", heard: ["yarn"]),
        Term(word: "Bun", heard: ["bun js"]),
        Term(word: "Deno", heard: ["deno", "dee no"]),
        Term(word: "Electron", heard: ["electron"]),
        Term(word: "Tauri", heard: ["tao ree", "tauri", "tory app"]),
        Term(word: "Expo", heard: ["expo"]),
        Term(word: "Flutter", heard: ["flutter"]),
        Term(word: "SwiftUI", heard: ["swift u i", "swift ui", "swiftui"]),
        Term(word: "Xcode", heard: ["x code", "ex code", "xcode"]),
        Term(word: "XcodeGen", heard: ["x code gen", "xcodegen", "xcode gen"]),
        Term(word: "iOS", heard: ["i o s", "ios"]),
        Term(word: "macOS", heard: ["mac o s", "mac os", "macos"]),
        Term(word: "iPadOS", heard: ["ipad o s", "ipad os"]),
        Term(word: "watchOS", heard: ["watch o s", "watch os"]),
        Term(word: "UIKit", heard: ["u i kit", "ui kit", "uikit"]),
        Term(word: "AppKit", heard: ["app kit", "appkit"]),
        // Languages & backends
        Term(word: "Python", heard: ["python"]),
        Term(word: "FastAPI", heard: ["fast a p i", "fast api", "fastapi"]),
        Term(word: "Django", heard: ["jango", "django"]),
        Term(word: "Flask", heard: ["flask"]),
        Term(word: "Laravel", heard: ["lara vel", "laravel", "lara vell"]),
        Term(word: "PHP", heard: ["p h p"]),
        Term(word: "Golang", heard: ["go lang", "golang"]),
        Term(word: "Rust", heard: ["rust lang"]),
        Term(word: "Kotlin", heard: ["kotlin", "cot lin"]),
        Term(word: "C#", heard: ["c sharp"]),
        Term(word: "C++", heard: ["c plus plus"]),
        Term(word: ".NET", heard: ["dot net"]),
        Term(word: "Spring Boot", heard: ["spring boot"]),
        Term(word: "Elixir", heard: ["elixir"]),
        Term(word: "Zig", heard: ["zig lang"]),
        // Infra, DevOps, cloud
        Term(word: "Docker", heard: ["docker"]),
        Term(word: "Docker Compose", heard: ["docker compose"]),
        Term(word: "Kubernetes", heard: ["kubernetes", "cooper netties", "cooper nettis", "k8s", "k 8 s"]),
        Term(word: "Nginx", heard: ["engine x", "engine ex", "nginx", "n ginx"]),
        Term(word: "Traefik", heard: ["traefik"]),
        Term(word: "Terraform", heard: ["terra form", "terraform"]),
        Term(word: "Ansible", heard: ["ansible"]),
        Term(word: "Jenkins", heard: ["jenkins"]),
        Term(word: "CI/CD", heard: ["c i c d", "ci cd", "c i slash c d", "ci slash cd"]),
        Term(word: "GitHub", heard: ["get hub", "git hub", "github"]),
        Term(word: "GitHub Actions", heard: ["github actions", "get hub actions"]),
        Term(word: "GitLab", heard: ["get lab", "git lab", "gitlab"]),
        Term(word: "Bitbucket", heard: ["bit bucket", "bitbucket"]),
        Term(word: "Vercel", heard: ["versal", "ver cell", "vercell", "verso", "vercel", "versel"]),
        Term(word: "Netlify", heard: ["net lify", "netlify", "netla fie"]),
        Term(word: "Cloudflare", heard: ["cloud flare", "cloudflare", "cloud flair"]),
        Term(word: "Cloudflare Workers", heard: ["cloudflare workers", "cloud flare workers"]),
        Term(word: "AWS", heard: ["a w s", "aws"]),
        Term(word: "S3", heard: ["s three"]),
        Term(word: "EC2", heard: ["e c two", "e c 2"]),
        Term(word: "DynamoDB", heard: ["dynamo d b", "dynamo db", "dynamodb"]),
        Term(word: "Azure", heard: ["azure"]),
        Term(word: "GCP", heard: ["g c p"]),
        Term(word: "Google Cloud", heard: ["google cloud"]),
        Term(word: "DigitalOcean", heard: ["digital ocean", "digitalocean"]),
        Term(word: "Hetzner", heard: ["hetzner", "het snur"]),
        Term(word: "Railway", heard: ["railway app"]),
        Term(word: "Render", heard: ["render dot com"]),
        Term(word: "Fly.io", heard: ["fly i o", "fly io", "fly dot io"]),
        Term(word: "Coolify", heard: ["cool ify", "coolify"]),
        Term(word: "Dokploy", heard: ["dock ploy", "dokploy"]),
        Term(word: "Portainer", heard: ["portainer", "port tainer"]),
        Term(word: "Proxmox", heard: ["prox mox", "proxmox"]),
        Term(word: "Tailscale", heard: ["tail scale", "tailscale"]),
        Term(word: "WireGuard", heard: ["wire guard", "wireguard"]),
        Term(word: "SSH", heard: ["s s h"]),
        Term(word: "SSL", heard: ["s s l"]),
        Term(word: "TLS", heard: ["t l s"]),
        Term(word: "HTTPS", heard: ["h t t p s"]),
        Term(word: "HTTP", heard: ["h t t p"]),
        Term(word: "DNS", heard: ["d n s"]),
        Term(word: "CDN", heard: ["c d n"]),
        Term(word: "VPN", heard: ["v p n"]),
        Term(word: "VPS", heard: ["v p s"]),
        Term(word: "IP address", heard: ["i p address"]),
        Term(word: "localhost", heard: ["local host", "localhost"]),
        Term(word: "webhook", heard: ["web hook", "webhook"]),
        Term(word: "webhooks", heard: ["web hooks", "webhooks"]),
        Term(word: "WebSocket", heard: ["web socket", "websocket"]),
        Term(word: "WebSockets", heard: ["web sockets", "websockets"]),
        Term(word: "cron job", heard: ["chron job", "cron job", "crown job"]),
        Term(word: "Grafana", heard: ["grafana", "gra fauna"]),
        Term(word: "Prometheus", heard: ["prometheus"]),
        Term(word: "Datadog", heard: ["data dog", "datadog"]),
        Term(word: "Sentry", heard: ["sentry"]),
        Term(word: "PostHog", heard: ["post hog", "posthog"]),
        Term(word: "Mixpanel", heard: ["mix panel", "mixpanel"]),
        // APIs, formats, general
        Term(word: "API", heard: ["a p i"]),
        Term(word: "APIs", heard: ["a p i s", "a p is"]),
        Term(word: "OpenAPI", heard: ["open a p i", "open api", "openapi"]),
        Term(word: "Swagger", heard: ["swagger"]),
        Term(word: "Postman", heard: ["post man", "postman"]),
        Term(word: "JSON", heard: ["j son", "jay son", "json"]),
        Term(word: "YAML", heard: ["yaml", "yam el", "yammel"]),
        Term(word: "TOML", heard: ["toml", "tom el"]),
        Term(word: "CSV", heard: ["c s v"]),
        Term(word: "XML", heard: ["x m l"]),
        Term(word: "PDF", heard: ["p d f"]),
        Term(word: "URL", heard: ["u r l"]),
        Term(word: "URLs", heard: ["u r ls", "u r l s"]),
        Term(word: "UUID", heard: ["u u i d", "uuid"]),
        Term(word: "CLI", heard: ["c l i"]),
        Term(word: "SDK", heard: ["s d k"]),
        Term(word: "SDKs", heard: ["s d ks", "s d k s"]),
        Term(word: "UI", heard: ["u i"]),
        Term(word: "UX", heard: ["u x"]),
        Term(word: "UI/UX", heard: ["u i u x", "ui ux", "u i slash u x"]),
        Term(word: "SaaS", heard: ["s a a s", "saas"]),
        Term(word: "MVP", heard: ["m v p"]),
        Term(word: "CRUD", heard: ["crud"]),
        Term(word: "ORM", heard: ["o r m"]),
        Term(word: "regex", heard: ["reg ex", "regex", "reg x"]),
        Term(word: "backend", heard: ["back end", "backend"]),
        Term(word: "frontend", heard: ["front end", "frontend"]),
        Term(word: "full-stack", heard: ["full stack", "fullstack"]),
        Term(word: "microservices", heard: ["micro services", "microservices"]),
        Term(word: "serverless", heard: ["server less", "serverless"]),
        Term(word: "middleware", heard: ["middle ware", "middleware"]),
        Term(word: "README", heard: ["read me file", "readme"]),
        Term(word: ".env", heard: ["dot env", "dot e n v"]),
        Term(word: "env var", heard: ["env var", "e n v var"]),
        Term(word: "env vars", heard: ["env vars", "e n v vars"]),
        Term(word: "PR", heard: ["p r"]),
        Term(word: "PRs", heard: ["p rs", "p r s"]),
        Term(word: "repo", heard: ["repo"]),
        Term(word: "MCP server", heard: ["m c p server", "mcp server"]),
        // Tools & products
        Term(word: "Figma", heard: ["fig ma", "figma", "fig mah"]),
        Term(word: "FigJam", heard: ["fig jam", "figjam"]),
        Term(word: "Framer", heard: ["framer"]),
        Term(word: "Webflow", heard: ["web flow", "webflow"]),
        Term(word: "WordPress", heard: ["word press", "wordpress"]),
        Term(word: "Shopify", heard: ["shopify", "shop ify"]),
        Term(word: "Notion", heard: ["notion"]),
        Term(word: "Slack", heard: ["slack"]),
        Term(word: "Jira", heard: ["jeera", "jira", "gira"]),
        Term(word: "Trello", heard: ["trello"]),
        Term(word: "Asana", heard: ["asana"]),
        Term(word: "ClickUp", heard: ["click up", "clickup"]),
        Term(word: "Airtable", heard: ["air table", "airtable"]),
        Term(word: "Zapier", heard: ["zap ier", "zapier", "zappier"]),
        Term(word: "n8n", heard: ["n eight n", "n 8 n", "n8n", "n a 10"]),
        Term(word: "Make.com", heard: ["make dot com"]),
        Term(word: "Retool", heard: ["re tool", "retool"]),
        Term(word: "Lovable", heard: ["loveable", "lovable"]),
        Term(word: "Bolt", heard: ["bolt new", "bolt dot new"]),
        Term(word: "v0", heard: ["v zero", "vee zero"]),
        Term(word: "Replit", heard: ["repl it", "replit", "rep lit"]),
        Term(word: "VS Code", heard: ["v s code", "vs code", "vscode", "visual studio code"]),
        Term(word: "Neovim", heard: ["neo vim", "neovim"]),
        Term(word: "Ghostty", heard: ["ghosty", "ghost tea", "ghostty", "ghost e"]),
        Term(word: "iTerm", heard: ["i term", "iterm", "eye term"]),
        Term(word: "iTerm2", heard: ["i term two", "iterm2", "i term 2"]),
        Term(word: "tmux", heard: ["t mux", "tmux", "tea mux"]),
        Term(word: "zsh", heard: ["z s h", "zish", "zsh", "z shell"]),
        Term(word: "Homebrew", heard: ["home brew", "homebrew"]),
        Term(word: "brew install", heard: ["brew install"]),
        Term(word: "Raycast", heard: ["ray cast", "raycast"]),
        Term(word: "1Password", heard: ["one password", "1 password", "1password"]),
        Term(word: "Obsidian", heard: ["obsidian"]),
        Term(word: "Arc browser", heard: ["arc browser"]),
        Term(word: "Zen Browser", heard: ["zen browser"]),
        Term(word: "Chrome DevTools", heard: ["chrome dev tools", "chrome devtools"]),
        Term(word: "DevTools", heard: ["dev tools", "devtools"]),
        Term(word: "Xcode Cloud", heard: ["xcode cloud", "x code cloud"]),
        Term(word: "TestFlight", heard: ["test flight", "testflight"]),
        Term(word: "App Store Connect", heard: ["app store connect"]),
        Term(word: "Google Analytics", heard: ["google analytics"]),
        Term(word: "Google Sheets", heard: ["google sheets"]),
        Term(word: "Google Drive", heard: ["google drive"]),
        Term(word: "Gmail", heard: ["g mail", "gmail"]),
        Term(word: "Outlook", heard: ["outlook"]),
        Term(word: "Microsoft Teams", heard: ["microsoft teams"]),
        Term(word: "WhatsApp", heard: ["whats app", "whatsapp", "what's app"]),
        Term(word: "Telegram", heard: ["telegram"]),
        Term(word: "LinkedIn", heard: ["linked in", "linkedin"]),
        Term(word: "YouTube", heard: ["you tube", "youtube"]),
        Term(word: "TikTok", heard: ["tik tok", "tiktok"]),
        Term(word: "Instagram", heard: ["instagram", "insta gram"]),
        Term(word: "Spotify", heard: ["spotify"]),
        Term(word: "Apple Music", heard: ["apple music"]),
        Term(word: "iPhone", heard: ["i phone", "iphone"]),
        Term(word: "iPad", heard: ["i pad", "ipad"]),
        Term(word: "MacBook", heard: ["mac book", "macbook"]),
        Term(word: "MacBook Air", heard: ["mac book air", "macbook air"]),
        Term(word: "MacBook Pro", heard: ["mac book pro", "macbook pro"]),
        Term(word: "Apple Silicon", heard: ["apple silicon"]),
        Term(word: "Apple Intelligence", heard: ["apple intelligence"]),
        Term(word: "Neural Engine", heard: ["neural engine"]),
        Term(word: "Wi-Fi", heard: ["wifi", "wi fi", "why fi"]),
        Term(word: "Bluetooth", heard: ["blue tooth", "bluetooth"]),
        Term(word: "AirPods", heard: ["air pods", "airpods"]),
        Term(word: "USB-C", heard: ["u s b c", "usb c", "usb see"]),
    ]

    /// Sorted longest-phrase-first so "claude code" wins over "claude".
    static let compiled: [(re: NSRegularExpression, word: String, probe: String)] = {
        var list: [(String, String)] = []
        for t in terms { for h in t.heard { list.append((h, t.word)) } }
        list.sort { $0.0.count > $1.0.count }
        return list.map { (TextUtil.regex("(?<![\\w.@/-])" + NSRegularExpression.escapedPattern(for: $0.0) + "(?![\\w.@/-])"), $0.1, String($0.0.split(separator: " ")[0])) }
    }()

    static func wordSet(_ s: String) -> Set<String> {
        Set(s.lowercased().split { !($0.isLetter || $0.isNumber) }.map(String.init))
    }

    public static func apply(_ text: String) -> String {
        var out = text
        var words = wordSet(text)
        for (re, word, probe) in compiled where words.contains(probe) {   // O(1) first-word probe before the regex
            let replaced = re.stringByReplacingMatches(in: out, range: NSRange(out.startIndex..., in: out), withTemplate: NSRegularExpression.escapedTemplate(for: word))
            if replaced != out { out = replaced; words = wordSet(out) }
        }
        return out
    }

    /// Terms present in `text` (to tell the LLM to preserve them).
    public static func termsPresent(in text: String) -> [String] {
        let lower = text.lowercased()
        return terms.map(\.word).filter { lower.contains($0.lowercased()) }
    }
}
